// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/data-fetching": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/users/:id": {
    params: {
      "id": string;
    };
  };
  "/files/*": {
    params: {
      "*": string;
    };
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/data-fetching" | "/dashboard" | "/dashboard/settings" | "/users/:id" | "/files/*" | "/login";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/data-fetching.tsx": {
    id: "routes/data-fetching";
    page: "/data-fetching";
  };
  "routes/dashboard/layout.tsx": {
    id: "routes/dashboard/layout";
    page: "/dashboard" | "/dashboard/settings";
  };
  "routes/dashboard/index.tsx": {
    id: "routes/dashboard/index";
    page: "/dashboard";
  };
  "routes/dashboard/settings.tsx": {
    id: "routes/dashboard/settings";
    page: "/dashboard/settings";
  };
  "routes/users/user.tsx": {
    id: "routes/users/user";
    page: "/users/:id";
  };
  "routes/files/$.tsx": {
    id: "routes/files/$";
    page: "/files/*";
  };
  "routes/_auth/layout.tsx": {
    id: "routes/_auth/layout";
    page: "/login";
  };
  "routes/_auth/login.tsx": {
    id: "routes/_auth/login";
    page: "/login";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home": typeof import("./src/routes/home.tsx");
  "routes/data-fetching": typeof import("./src/routes/data-fetching.tsx");
  "routes/dashboard/layout": typeof import("./src/routes/dashboard/layout.tsx");
  "routes/dashboard/index": typeof import("./src/routes/dashboard/index.tsx");
  "routes/dashboard/settings": typeof import("./src/routes/dashboard/settings.tsx");
  "routes/users/user": typeof import("./src/routes/users/user.tsx");
  "routes/files/$": typeof import("./src/routes/files/$.tsx");
  "routes/_auth/layout": typeof import("./src/routes/_auth/layout.tsx");
  "routes/_auth/login": typeof import("./src/routes/_auth/login.tsx");
};